#!/usr/bin/env node
/**
 * Generate the wiki's Content-Security-Policy from the built output.
 *
 * Astro has a native `security.csp` option, and it does not work here: it only
 * hashes scripts that pass through its own pipeline, so the six scripts
 * Starlight writes straight into the HTML (theme provider, search modal,
 * sidebar persistence) end up blocked by the policy Astro itself emitted.
 * Verified: 4 of 10 inline scripts covered.
 *
 * Reading the real dist/ instead cannot miss anything, because it hashes what
 * is actually on the page. Emitting a header rather than a meta tag also means
 * frame-ancestors is honoured, which browsers ignore in <meta>.
 *
 * Writes an nginx snippet consumed by deploy/preview/nginx-wiki.conf.
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const dist = join(root, 'dist');
const out = join(root, '..', 'deploy', 'preview', 'nginx-wiki-csp.conf');

const walk = (d) => readdirSync(d).flatMap((e) => {
  const p = join(d, e);
  return statSync(p).isDirectory() ? walk(p) : [p];
});

const sha = (s) => "'sha256-" + createHash('sha256').update(s, 'utf8').digest('base64') + "'";

const scripts = new Set();
let pages = 0;

for (const file of walk(dist)) {
  if (extname(file) !== '.html') continue;
  pages++;
  const html = readFileSync(file, 'utf8');
  for (const [, attrs, body] of html.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/gi)) {
    if (/\ssrc=/i.test(attrs)) continue;
    if (/application\/ld\+json/i.test(attrs)) continue;   // data, not code
    scripts.add(sha(body));
  }
}

// style-src keeps 'unsafe-inline' deliberately. Starlight sets inline style
// attributes for sidebar and code-block layout, and CSP only accepts hashes for
// those alongside 'unsafe-hashes', which weakens script handling too. An inline
// style cannot execute code, so this is the smaller exposure by a wide margin,
// and script-src stays fully hash-pinned.
const csp = [
  "default-src 'self'",
  // 'wasm-unsafe-eval' is what Pagefind's index needs: it runs as WebAssembly,
  // which CSP refuses to compile under a hash-pinned script-src without this
  // token. It permits WASM compilation only, not eval() or Function().
  `script-src 'self' 'wasm-unsafe-eval' ${[...scripts].sort().join(' ')}`,
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data:",
  "font-src 'self'",
  "connect-src 'self'",
  "frame-src https://www.youtube-nocookie.com",
  "form-action 'self'",
  "frame-ancestors 'none'",
  "base-uri 'none'",
  "object-src 'none'",
  "upgrade-insecure-requests",
].join('; ');

writeFileSync(out, `# Generated by wiki/scripts/gen-csp.mjs. Do not edit.\n` +
  `# ${scripts.size} inline script hashes across ${pages} pages.\n` +
  `add_header Content-Security-Policy "${csp}" always;\n`);

console.log(`  csp: ${scripts.size} script hashes from ${pages} pages -> deploy/preview/nginx-wiki-csp.conf`);
