#!/usr/bin/env python3
"""Regenerate the Zola logo partial from brand/logo-horizontal.svg.

The lockup has to be inlined rather than linked: its wordmark path is set to
currentColor so it follows the theme, and currentColor does not cross into an
SVG referenced by <img>. Astro imports the same file directly as a component,
so brand/ stays the single source for both tracks.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
src = (ROOT / "brand/logo-horizontal.svg").read_text()
svg = re.sub(r"<svg ", '<svg class="brand__logo" role="img" aria-label="EndeavourOS" ', src, count=1)
header = (
    "{#- Generated by `make sync` from brand/logo-horizontal.svg. Do not edit.\n"
    "   Inlined rather than linked because the wordmark path uses currentColor,\n"
    "   which does not cross into an <img>-referenced SVG. -#}\n"
)
out = ROOT / "zola/templates/partials/logo.html"
out.write_text(header + svg)
print(f"  {out.relative_to(ROOT)} regenerated ({len(header) + len(svg)} bytes)")
